name: Cloudfalre Worker Deploy
on:
  push:
    branches:
      - master
  repository_dispatch:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          run_install: true
          version: 9

      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/wrangler-action@v3.1.0
        with:
          # The Wrangler command (along with any arguments) you wish to run. Multiple Wrangler commands can be run by separating each command with a newline. Defaults to `"deploy"`.
          command: 'deploy --keep-vars'
